name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: METRICS_TOKEN
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: AritxOnly
          template: classic
          # 注意拼写要正确
          # base: header, repositories, activities
          # plugin_calendar: yes
          # plugin_calendar_limit: 2
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
